### PR TITLE
test for exclusion mask

### LINKED ISSUE #102: add exclusion test -- test_simplify_network_small_exclude()`
* add exclusion test for the Appalachicola scenario
* `test_simplify_network_small_exclude()` -- in [`test_simplify.py`](https://github.com/uscuni/sgeop/blob/8e10d48cf1197e945dc210bc721c9e0c6f974ea1/sgeop/tests/test_simplify.py)

### LINKED ISSUE #106: apalachicola testing -- most edge cases resolved when sorting by geometry
* apalachicola testing -- most edge cases resolved when sorting by geometry

xref:
* #74 
* #75 
* #77 
* #102

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* resolves #102 
* resolves #106

### CODE REVIEW

**Comment by jGaboardi** [comment]
So these new "edge cases" are not only edge cases in terms of coordinate order, wild precision, etc. --> The actual index order in the resultant dataframes are different. I have confirmed that the returned geometries are equivalent (within tolerance) across OSs, both visually and programmatically – but in different orders.

**Comment by jGaboardi** [comment]
macOS (ARM) vs. Ubuntu -- complete

simplified_exclusion_mask_comparison_complete

**Comment by jGaboardi** [comment]
macOS (ARM) vs. Ubuntu -- "bad" subset

simplified_exclusion_mask_comparison_bad_subset

**Comment by jGaboardi** [comment]
Index sort

simplified_exclusion_mask_comparison_bad_subset_index_sort

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
