### PR TITLE
pin minimum `momepy` to 0.9.0

### LINKED ISSUE #101: bump minimum `momepy` to `v0.9.0`
bump minimum `momepy` to `v0.9.0` once that hits conda-forge

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #101

### CODE REVIEW

**Comment by martinfleis** [comment]
Because of https://github.com/pysal/momepy/pull/666?

**Comment by jGaboardi** [comment]
#103 failure should clear after this.

**Comment by jGaboardi** [comment]
@martinfleis Is there are reason we should not pin `momepy=0.9.0`? It also helps moving toward https://github.com/uscuni/sgeop/issues/68.

**Comment by martinfleis** [comment]
Not really. Let's pin.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
