### PR TITLE
Create CONTRIBUTING.md -- document procedure

### LINKED ISSUE #4: Add contributing guidelines document
Add contributing guidelines document

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* resolves #4 
* kicks off #7 – gives a structure, but we can work on ironing out the wording if needed. I welcome input on language, other sections, etc.

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]

**Comment by jGaboardi** [comment]
Let's wait for @anastassiavybornova to read/review to see if she has any suggestions.

**Review by anastassiavybornova — APPROVED** [review]
looks good to me! but we do plan to make the contributing guidelines more detailed than this, right? (otherwise my comment would be "should be more detailed" 😄  )

**Comment by martinfleis** [comment]
I like this template https://clustergram.readthedocs.io/en/stable/contributing.html but that can wait.

**Comment by jGaboardi** [comment]
> we do plan to make the contributing guidelines more detailed than this, right?

Yes, this is merely a first pass to get it started

> I like this template https://clustergram.readthedocs.io/en/stable/contributing.html but that can wait.

I'll open a new issue where we can discuss how to flesh out further.

**Pull request merged**
