### PR TITLE
small integrated testing data - apalachicola, fl

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR adds small input and observed datasets of beautiful [apalachicola, fl](https://en.wikipedia.org/wiki/Apalachicola,_Florida) to ensure full algorithm passes while creating full testing suite // refactoring.

xref #28 

***this should be reviewed & merged before looking back into #27***

### CODE REVIEW

**Comment by jGaboardi** [comment]
It would help if I added the actual test... 🙄

**Comment by martinfleis** [comment]
It is a precision issue. I just debugged it on ubuntu and it will likely be related to some differences deep in the stack. It is nearly the same, geopandas just uses fixed precision and we need to be a bit more flexible than that.

**Review by jGaboardi — COMMENTED** [review]
[approved by me]

**Comment by jGaboardi** [comment]
@anastassiavybornova I am not sure how involved you'd like to be in these [develop -> test -> review] cycles for our project, but I'll leave this open bit longer in case you'd like to do a review + official approval.

**Comment by martinfleis** [comment]
I still want to check the actual data

**Comment by jGaboardi** [comment]
I like to use Apalachicola in various testing applications because it is a very small, contained area. We probably add more areas to hit more lines of code, unless we want to use a full FUA from over in `simplification`.

Thoughts on that?

**Comment by martinfleis** [comment]
Fine with me. I just want to check the outcome as with small areas, the artifact detection heuristics tends to struggle to identify the threshold.

**Comment by jGaboardi** [comment]
OK, we'll stick with Appalachicola for now (pending your review) then think about more areas later.

**Comment by anastassiavybornova** [comment]
> @anastassiavybornova I am not sure how involved you'd like to be in these [develop -> test -> review] cycles for our project, but I'll leave this open bit longer in case you'd like to do a review + official approval.

@jGaboardi thanks for checking back, happy to be involved but realistically my contributions will be of limited urgency :D so if my pending review is a bottleneck timewise - don't wait for it for too long, i trust the 2 of you here



> These failures are most definitely an OS issue, but I don't have access to Ubuntu or Windows to troubleshoot. Any ideas for diagnosing & fixing? While this specific test is that big of a deal, we'll absolutely want a robust cross-OS testing solution in general.
> 
> @martinfleis & @anastassiavybornova

i'm setting up windows (for another project where we also need to test windows compatibility) so i can try to test there

**Comment by jGaboardi** [comment]
> not needed imo, the only different was apple silicon.

I was the actual troublemaker...

**Review by martinfleis — APPROVED** [review]
I think that this is fine. It just to be noted that this example covers only a small fraction of cases hence only a small fraction of code.

**Comment by jGaboardi** [comment]
> I think that this is fine. It just to be noted that this example covers only a small fraction of cases hence only a small fraction of code.

Some maybe we should keep this a small example since it runs very quickly, but include one of the FUA from `simplification` soon?

**Pull request merged**
